### ISSUE TITLE
LateXML not building properly on Mac

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#1]
Since updating the build scripts to the latest, LateXML no longer builds on MacOS: Perl library XML::LibXSLT fails to install during execution.

https://github.com/metanorma/metanorma-standoc/runs/394188796

**Comment by opoudjis** [comment]
Please action, this is interfering with GitHub Action testing

**Comment by CAMOBAP** [comment]
Done

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-build-scripts/commit/7c7ac8009e1ef94799b269445d200779394bf709

**Comment by ronaldtse** [comment]
Thanks!
