### ISSUE TITLE
Enable XSL:FO PDF processing for metanorma gem

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#19]
... and for the gems using XSL:FO PDF: nist, iec, iso, itu, unece.

The tickets to port that functionality into the three OS's are:

https://github.com/metanorma/chocolatey-metanorma/issues/38
https://github.com/metanorma/metanorma-macos-setup/issues/9
https://github.com/metanorma/metanorma-linux-setup/issues/21

**Comment by CAMOBAP** [comment]
Done in the scope of https://github.com/metanorma/metanorma-build-scripts/issues/38
