### ISSUE TITLE
soffice not being retrieved in Win, Ubuntu for reverse-asciidoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#2]
It looks like @w00lf had hard coded these to the build scripts, but had not informed you to update them, so they got wiped when I did the build script updates: https://github.com/metanorma/reverse_adoc/commit/7262ce92efe51c0941c38729150ae82cfc11b5b0#diff-a77b4f53dac18d1e289021f245022811

Could you please update the build scripts against what @w00lf had earlier?

@w00lf: as I'd indicated, the build scripts (.github/workflows/*.yml) are updated by @CAMOBAP795 and automatically propagated throughout  Metanorma when the ci-master script is run. That's why you can't update those scripts manually.

**Comment by CAMOBAP** [comment]
@opoudjis actually I have reviewed those changes, so it's my mistake(

**Comment by opoudjis** [comment]
Please action so that we can get rspec working on Github Actions

**Comment by CAMOBAP** [comment]
Done

**Comment by opoudjis** [comment]
... WAIT!

Why is this change in https://github.com/metanorma/reverse_adoc and not here in ci-master? The problem last time was that a ci-master update overwrote what was in reverse-adoc; the GitHub Action scripts surely need to live in ci-master.

**Comment by CAMOBAP** [comment]
now I have added it here https://github.com/metanorma/metanorma-build-scripts/commit/02497df508e2076fce41fbeb5494df744ae60abd

To be on the same page:
 - https://github.com/metanorma/ci-master - doesn't contain any configuration, just a tool which applies them to actual repos
 - https://github.com/metanorma/metanorma-build-scripts - contains only CI configuration with [config/ci.yml](https://github.com/metanorma/metanorma-build-scripts/blob/master/ci-master/config/ci.yml)mapping file which 

Closing this one
