### ISSUE TITLE
Issue with overriding repositories that have modified files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ci-master#22]
Some repositories contain very similar but different Makefiles, such as iso-10303-2 -- it has some targets that are specific to it, such as for file generation outside Metanorma.

Is it possible to have some hidden file, e.g. `.cimas-block` so that Cimas doesn't update it (i.e. even if we kept it in the config, it still doesn't update it)?

**Comment by CAMOBAP** [comment]
There are no difficulties in implementing it, but I think is more simple and clear to keep the configuration in one place https://github.com/metanorma/metanorma-build-scripts/blob/main/cimas-config/cimas.yml, and if a file needs to be excluded, much simpler just remove if from cimas.yml
