### ISSUE TITLE
Need exception to gem caching

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#23]
The recent modifications to used cached gems, in the feature/bundler-cache-and-brew-install-metanorma branches, have made compilation much quicker. However they have introduced a new problem.

The release of the multiple gems generated by our team needs GitHub Actions to receive up to date releases of our own gems, since they are released in succession, and pre-release testing of one depends on the release of the gems it depends on. In the case of MacOs and Ubuntu, there is a lag of at least 32 hours between release and the cache being updated.

The simplest solution here is to except all metanorma, relaton, plurimath gems from caching, and to fetch them direct from rubygems to GitHub Actions. Somehow.

**Comment by CAMOBAP** [comment]
According to what I see caching doesn't work on windows this is why we have no problem. 

As far as I understand the caching logic doesn't update gems if new versions available. 

Also moving back to Gemfile.lock also isn't possible for us https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

So I see only one option here, remove caching 

@opoudjis @ronaldtse please share your thoughts

**Comment by opoudjis** [comment]
....

Avoiding Gemfile.lock is a preference for testing, and we have been bitten by it on Travis, which is why we removed the file, but it's worth revisiting.

So https://github.com/ruby/setup-ruby#caching-bundle-install-manually will not work?

And I'm OK to work with vendor/ local config if that's what it will take. Cf. https://github.com/github/view_component/pull/460 and https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html . And we could configure the local "rake release" to update the vendor local gem cache: maybe, switch to local cache for bundler, update vendor bundle, then switch back to default bundler config, and push.

**Comment by CAMOBAP** [comment]
> So https://github.com/ruby/setup-ruby#caching-bundle-install-manually will not work?

as far as I understand ruby/setup-ruby use absolutely the same way, let me check bundler CLI API, I cannot believe that there is no way to query RubyGems just to check is the cached gem latest one or not

**Comment by CAMOBAP** [comment]
Implemented https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#a-ruby-gem
