### ISSUE TITLE
Broken "commits since" in releases page of metanorma gems

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#25]
We have switched the default branch of most metanorma repositories from `master` to `main`.

If a repository still has been left on `master`, or if it was created from the beginning as `main`, the "commits since this release" header still displays:

https://github.com/metanorma/html2doc/releases/tag/v1.1.2
https://github.com/metanorma/metanorma-utils/releases/tag/v1.2.2

However, for repositories like metanorma-standoc, where we have shifted the default repository, the header no longer displays:

https://github.com/metanorma/metanorma-standoc/releases/tag/v1.9.3

This makes it difficult to compile release notes.

This is a known issue, and the best Github has come up with is a workaround in the GitHub actions config for the repository, whereby release workflows (such as `rake release`) need to trigger release creation on the GitHub API, using the `target_commitish` parameter:

https://github.community/t/x-commits-to-master-since-this-release-is-missing/618/9 
https://github.community/t/bug-commit-since-release-doesnt-use-default-branch-master-hardcoded/155923/11 
https://github.com/actions/create-release/blob/main/README.md for example workflow

**Comment by CAMOBAP** [comment]
Doesn't looks related to cimas itself, I'm not sure if it can be fixed on cimas side
