### ISSUE TITLE
Remove Gemfile.devel from .gitignore

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#29]
We will be using Gemfile.devel from now on to ensure that PRs under development import the correct dependencies for GHA. So  excluding Gemfile.devel through gitignore would be counterproductive.

It would be nice if we could ensure that Gemfile.devel is never included in a release, but I don't know if that should be locally implemented code, through rake.

**Comment by CAMOBAP** [comment]
AFAIK it's excluded from metanorma-cli where I used it last time, there is not magic that can remove it from each metanorma-* (flavors) so let's remove it on-demand
