### ISSUE TITLE
Rubocop update

### ISSUE THREAD

**Issue by opoudjis** [metanorma/ci-master#32]
From metanorma gem, running rubocop:

````
Warning: obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma/.rubocop-https---raw-githubusercontent-com-riboseinc-oss-guides-master-ci-rubocop-yml
`IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.
Warning: Metrics/BlockLength does not support IgnoredMethods parameter.

Supported parameters are:

  - Enabled
  - CountComments
  - Max
  - CountAsOne
  - AllowedMethods
  - AllowedPatterns
  - Exclude

Warning: obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma/.rubocop.yml
`IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.
Warning: Metrics/BlockLength does not support IgnoredMethods parameter.

Supported parameters are:

  - Enabled
  - CountComments
  - Max
  - CountAsOne
  - AllowedMethods
  - AllowedPatterns
  - Exclude
````

**Comment by CAMOBAP** [comment]
@opoudjis to be on the same page what are the `rubocop` and `rubocop-*` related gems are you using?

Because we don't list them explicitly in `Gemfile` do we hae any agreement on min, max version that we should support?

cc @ronaldtse

**Comment by opoudjis** [comment]
Metanorma in gemspec has frozen rubocop at 1.5.2. Which... was a long time ago (Dec 2020), but I was never told to update it.

Relaton FWIW is frozen in gemspec at rubocop 1.17 (Jun 2021).

If we have a cross-Ribose policy on rubocop versioning, versions should be set outside of gemfiles somehow. But I don't know how feasible that is.

**Comment by opoudjis** [comment]
Ah. The gemspec does that, but I run command line "rubocop", which of course is merely the latest available online.

So I should be running bundle exec rubocop. I don't mind doing that, but we should have a min and max version of rubocop anyway, and I don't think it should be from 2020.

**Comment by CAMOBAP** [comment]
@opoudjis agree with you

Because we actually depend on https://github.com/riboseinc/oss-guides/ are you okay if we move the discussion there?

**Comment by opoudjis** [comment]
Sure

**Comment by CAMOBAP** [comment]
Similar topic https://github.com/riboseinc/oss-guides/issues/54
