### ISSUE TITLE
Change default branch to main and add metanorma@ribose.com to the gem

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci-master#35]
> cimas 0.2.0 built to pkg/cimas-0.2.0.gem.
> Tag v0.2.0 has already been created.
> Pushing gem to https://rubygems.org.../
> You do not have permission to push to this gem. Ask an owner to add you with: gem owner cimas --add metanorma@ribose.com
> Error: Process completed with exit code 1.

Full log: https://github.com/metanorma/cimas/actions/runs/9172420822/job/25218877158#step:10:19

**Comment by ronaldtse** [comment]
Added gem owner and renamed branch.
